// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.tutorial.protos;

public final class ClassProtos {
  private ClassProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Professors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Professors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Professor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Professor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010tutorial\"4\n\nProfessors\022&\n\t" +
      "professor\030\001 \003(\0132\023.tutorial.Professor\"\221\001\n" +
      "\tProfessor\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\r\n\005" +
      "email\030\003 \001(\t\022\021\n\tbirthDate\030\004 \001(\t\022\023\n\013phoneN" +
      "umber\030\005 \001(\t\022\017\n\007address\030\006 \001(\t\022\"\n\007student\030" +
      "\007 \003(\0132\021.tutorial.Student\"\206\001\n\007Student\022\n\n\002" +
      "id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013phoneNumber\030\003 " +
      "\001(\t\022\016\n\006gender\030\004 \001(\t\022\021\n\tbirthDate\030\005 \001(\t\022\030" +
      "\n\020registrationDate\030\006 \001(\t\022\017\n\007address\030\007 \001(" +
      "\tB,\n\033com.example.tutorial.protosB\013ClassP" +
      "rotosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Professors_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Professors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Professors_descriptor,
        new java.lang.String[] { "Professor", });
    internal_static_tutorial_Professor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Professor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Professor_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "BirthDate", "PhoneNumber", "Address", "Student", });
    internal_static_tutorial_Student_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "PhoneNumber", "Gender", "BirthDate", "RegistrationDate", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
