// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.tutorial.protos;

public interface ProfessorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Professors)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  java.util.List<com.example.tutorial.protos.Professor> 
      getProfessorList();
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  com.example.tutorial.protos.Professor getProfessor(int index);
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  int getProfessorCount();
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  java.util.List<? extends com.example.tutorial.protos.ProfessorOrBuilder> 
      getProfessorOrBuilderList();
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  com.example.tutorial.protos.ProfessorOrBuilder getProfessorOrBuilder(
      int index);
}
