// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.tutorial.protos;

/**
 * Protobuf type {@code tutorial.Professors}
 */
public final class Professors extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.Professors)
    ProfessorsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Professors.newBuilder() to construct.
  private Professors(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Professors() {
    professor_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Professors();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Professors(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              professor_ = new java.util.ArrayList<com.example.tutorial.protos.Professor>();
              mutable_bitField0_ |= 0x00000001;
            }
            professor_.add(
                input.readMessage(com.example.tutorial.protos.Professor.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        professor_ = java.util.Collections.unmodifiableList(professor_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.tutorial.protos.ClassProtos.internal_static_tutorial_Professors_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.tutorial.protos.ClassProtos.internal_static_tutorial_Professors_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.tutorial.protos.Professors.class, com.example.tutorial.protos.Professors.Builder.class);
  }

  public static final int PROFESSOR_FIELD_NUMBER = 1;
  private java.util.List<com.example.tutorial.protos.Professor> professor_;
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.tutorial.protos.Professor> getProfessorList() {
    return professor_;
  }
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.tutorial.protos.ProfessorOrBuilder> 
      getProfessorOrBuilderList() {
    return professor_;
  }
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  @java.lang.Override
  public int getProfessorCount() {
    return professor_.size();
  }
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  @java.lang.Override
  public com.example.tutorial.protos.Professor getProfessor(int index) {
    return professor_.get(index);
  }
  /**
   * <code>repeated .tutorial.Professor professor = 1;</code>
   */
  @java.lang.Override
  public com.example.tutorial.protos.ProfessorOrBuilder getProfessorOrBuilder(
      int index) {
    return professor_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < professor_.size(); i++) {
      output.writeMessage(1, professor_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < professor_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, professor_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.tutorial.protos.Professors)) {
      return super.equals(obj);
    }
    com.example.tutorial.protos.Professors other = (com.example.tutorial.protos.Professors) obj;

    if (!getProfessorList()
        .equals(other.getProfessorList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProfessorCount() > 0) {
      hash = (37 * hash) + PROFESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getProfessorList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.tutorial.protos.Professors parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tutorial.protos.Professors parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tutorial.protos.Professors parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tutorial.protos.Professors parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.tutorial.protos.Professors parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tutorial.protos.Professors parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.tutorial.protos.Professors prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.Professors}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.Professors)
      com.example.tutorial.protos.ProfessorsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.protos.ClassProtos.internal_static_tutorial_Professors_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.protos.ClassProtos.internal_static_tutorial_Professors_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.protos.Professors.class, com.example.tutorial.protos.Professors.Builder.class);
    }

    // Construct using com.example.tutorial.protos.Professors.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProfessorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (professorBuilder_ == null) {
        professor_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        professorBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.tutorial.protos.ClassProtos.internal_static_tutorial_Professors_descriptor;
    }

    @java.lang.Override
    public com.example.tutorial.protos.Professors getDefaultInstanceForType() {
      return com.example.tutorial.protos.Professors.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.tutorial.protos.Professors build() {
      com.example.tutorial.protos.Professors result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.tutorial.protos.Professors buildPartial() {
      com.example.tutorial.protos.Professors result = new com.example.tutorial.protos.Professors(this);
      int from_bitField0_ = bitField0_;
      if (professorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          professor_ = java.util.Collections.unmodifiableList(professor_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.professor_ = professor_;
      } else {
        result.professor_ = professorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.tutorial.protos.Professors) {
        return mergeFrom((com.example.tutorial.protos.Professors)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.tutorial.protos.Professors other) {
      if (other == com.example.tutorial.protos.Professors.getDefaultInstance()) return this;
      if (professorBuilder_ == null) {
        if (!other.professor_.isEmpty()) {
          if (professor_.isEmpty()) {
            professor_ = other.professor_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProfessorIsMutable();
            professor_.addAll(other.professor_);
          }
          onChanged();
        }
      } else {
        if (!other.professor_.isEmpty()) {
          if (professorBuilder_.isEmpty()) {
            professorBuilder_.dispose();
            professorBuilder_ = null;
            professor_ = other.professor_;
            bitField0_ = (bitField0_ & ~0x00000001);
            professorBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProfessorFieldBuilder() : null;
          } else {
            professorBuilder_.addAllMessages(other.professor_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.tutorial.protos.Professors parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.tutorial.protos.Professors) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.tutorial.protos.Professor> professor_ =
      java.util.Collections.emptyList();
    private void ensureProfessorIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        professor_ = new java.util.ArrayList<com.example.tutorial.protos.Professor>(professor_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.tutorial.protos.Professor, com.example.tutorial.protos.Professor.Builder, com.example.tutorial.protos.ProfessorOrBuilder> professorBuilder_;

    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public java.util.List<com.example.tutorial.protos.Professor> getProfessorList() {
      if (professorBuilder_ == null) {
        return java.util.Collections.unmodifiableList(professor_);
      } else {
        return professorBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public int getProfessorCount() {
      if (professorBuilder_ == null) {
        return professor_.size();
      } else {
        return professorBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public com.example.tutorial.protos.Professor getProfessor(int index) {
      if (professorBuilder_ == null) {
        return professor_.get(index);
      } else {
        return professorBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder setProfessor(
        int index, com.example.tutorial.protos.Professor value) {
      if (professorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorIsMutable();
        professor_.set(index, value);
        onChanged();
      } else {
        professorBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder setProfessor(
        int index, com.example.tutorial.protos.Professor.Builder builderForValue) {
      if (professorBuilder_ == null) {
        ensureProfessorIsMutable();
        professor_.set(index, builderForValue.build());
        onChanged();
      } else {
        professorBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder addProfessor(com.example.tutorial.protos.Professor value) {
      if (professorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorIsMutable();
        professor_.add(value);
        onChanged();
      } else {
        professorBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder addProfessor(
        int index, com.example.tutorial.protos.Professor value) {
      if (professorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorIsMutable();
        professor_.add(index, value);
        onChanged();
      } else {
        professorBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder addProfessor(
        com.example.tutorial.protos.Professor.Builder builderForValue) {
      if (professorBuilder_ == null) {
        ensureProfessorIsMutable();
        professor_.add(builderForValue.build());
        onChanged();
      } else {
        professorBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder addProfessor(
        int index, com.example.tutorial.protos.Professor.Builder builderForValue) {
      if (professorBuilder_ == null) {
        ensureProfessorIsMutable();
        professor_.add(index, builderForValue.build());
        onChanged();
      } else {
        professorBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder addAllProfessor(
        java.lang.Iterable<? extends com.example.tutorial.protos.Professor> values) {
      if (professorBuilder_ == null) {
        ensureProfessorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, professor_);
        onChanged();
      } else {
        professorBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder clearProfessor() {
      if (professorBuilder_ == null) {
        professor_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        professorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public Builder removeProfessor(int index) {
      if (professorBuilder_ == null) {
        ensureProfessorIsMutable();
        professor_.remove(index);
        onChanged();
      } else {
        professorBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public com.example.tutorial.protos.Professor.Builder getProfessorBuilder(
        int index) {
      return getProfessorFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public com.example.tutorial.protos.ProfessorOrBuilder getProfessorOrBuilder(
        int index) {
      if (professorBuilder_ == null) {
        return professor_.get(index);  } else {
        return professorBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public java.util.List<? extends com.example.tutorial.protos.ProfessorOrBuilder> 
         getProfessorOrBuilderList() {
      if (professorBuilder_ != null) {
        return professorBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(professor_);
      }
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public com.example.tutorial.protos.Professor.Builder addProfessorBuilder() {
      return getProfessorFieldBuilder().addBuilder(
          com.example.tutorial.protos.Professor.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public com.example.tutorial.protos.Professor.Builder addProfessorBuilder(
        int index) {
      return getProfessorFieldBuilder().addBuilder(
          index, com.example.tutorial.protos.Professor.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.Professor professor = 1;</code>
     */
    public java.util.List<com.example.tutorial.protos.Professor.Builder> 
         getProfessorBuilderList() {
      return getProfessorFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.tutorial.protos.Professor, com.example.tutorial.protos.Professor.Builder, com.example.tutorial.protos.ProfessorOrBuilder> 
        getProfessorFieldBuilder() {
      if (professorBuilder_ == null) {
        professorBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.tutorial.protos.Professor, com.example.tutorial.protos.Professor.Builder, com.example.tutorial.protos.ProfessorOrBuilder>(
                professor_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        professor_ = null;
      }
      return professorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.Professors)
  }

  // @@protoc_insertion_point(class_scope:tutorial.Professors)
  private static final com.example.tutorial.protos.Professors DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.tutorial.protos.Professors();
  }

  public static com.example.tutorial.protos.Professors getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Professors>
      PARSER = new com.google.protobuf.AbstractParser<Professors>() {
    @java.lang.Override
    public Professors parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Professors(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Professors> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Professors> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.tutorial.protos.Professors getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

